### ISSUE TITLE
pulled in your changes to my fork

### ISSUE THREAD

**Issue by sandsmark** [withmorten/AGE#1]
fwiw, I pulled in your changes to my fork if AGE (I have some other improvements as well, so it was more of a hopefully okay redo: https://github.com/sandsmark/AGE), as well as your improvements to genieutils (also a redo, luckily it was a smaller patch): https://github.com/sandsmark/genieutils

**Comment by withmorten** [comment]
Yeah sure that's great! I'd hate for all branches to have weird different features.

Btw how did you do that? I added tapsas changes manually by diffing with WinMerge ... which doesn't seem the right way to do it ...

**Comment by sandsmark** [comment]
git fetch, git cherry-pick, removed the conflicting code (i. e. copied in the .cpp file from my master branch), and manually copied in the changes from your commit (and then fixed it up, e. g. the variables I had renamed, replacing lexical_cast with std::to_string, etc.). I guess that's more or less the same you did, and I did the same with Tapsa's changes.
